name: ©️ copyright removal request
description: request to remove content
labels: ['remove stream']
body:
  - type: input
    attributes:
      label: your full legal name
    validations:
      required: true

  - type: dropdown
    attributes:
      label: are you the copyright holder or authorized to act on the copyright owner's behalf?
      description: we cannot process your request unless it is submitted by the copyright owner or an agent authorized to act on behalf of the copyright owner.
      options:
        - Yes, I am the copyright holder.
        - Yes, I am authorized to act on the copyright owner's behalf.
        - No.
    validations:
      required: true

  - type: textarea
    attributes:
      label: please describe the nature of your copyright ownership or authorization to act on the owner's behalf.
    validations:
      required: true

  - type: textarea
    attributes:
      label: please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.
    validations:
      required: true

  - type: textarea
    attributes:
      label: what content should be removed? please specify the URL for each item.
    validations:
      required: true

  - type: textarea
    attributes:
      label: any additional information we need to know?
