name: edit stream
description: request to edit stream
title: 'Edit: '
labels: ['edit stream']

body:
  - type: input
    attributes:
      label: new stream URL
      description: new link to the stream if you are editing this
      placeholder: 'https://television.net/index.m3u8'
      
  - type: input
    attributes:
      label: channel name
      description: "full name of the channel."
      placeholder: 'Disney XD'
      required: true

  - type: dropdown
    attributes:
      label: quality
      description: maximum video resolution available on the link
      options:
        - 1080p
        - 720p
        - 576p
        - 480p
        - 360p
        
  - type: textarea
    attributes:
      label: Notes
      placeholder: 'anything we should know? geoblocked, not 24/7, etc'
