name: add a stream
description: request to add a new stream into the playlist
title: 'Add: '
labels: ['streams:add']

body:
  - type: input
    attributes:
      label: channel name
      required: true
      
  - type: input
    attributes:
      label: stream URL
      placeholder: 'https://example.net/file.m3u8'
    validations:
      required: true

  - type: textarea
    attributes:
      label: stuff we should know about the stream (is it geoblocked, not 24/7, etc)
      description: "any notes?"


  - type: checkboxes
    attributes:
      label: contributing guide
      description: 'please read [this](https://github.com/frostiptv/frostiptv.github.io/blob/main/README.md) before posting a request'
      options:
        - label: i've read it
          required: true
