name: report broken stream
description: report a broken or unstable stream
title: 'remove: '
labels: ['remove stream']

body:
  - type: input
    attributes:
      label: broken stream
      description: please specify the broken link
      placeholder: 'https://cookies.net/channel.m3u8'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: what happened to the stream?
      options:
        - not loading
        - constantly interrupts/lagging
        - stuck at a single frame
        - looped
        - no audio
        - other
    validations:
      required: true

  - type: textarea
    attributes:
      label: notes
      placeholder: 'anything else we should know?'
